import Provider from "~/provider/provider";

import type { Metadata } from "next";
import "~/styles/globals.css";

export const metadata: Metadata = {
    title: "F2",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico"
    }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
